### ISSUE TITLE
Allow clients to set the internal timestamp

### ISSUE THREAD

**Issue by harrisonhjones** [prozz/aws-embedded-metrics-golang#3]
First off: thanks for this great little library. It's saved me some time writing it myself.

I'm happy to send in a PR for this but wanted to make sure it would be accepted before sending.

**Problem**

I'd like to be able to set the timestamp when creating a new emf. It's currently initalized to `time.Now().UnixNano() / int64(time.Millisecond)`. This complicates two different situations:
1. When I want to emit logs for past/future events.
2. When I want to test log entries against static values.

In the mean time I've been doing the extremely hacky:
```go
rf := reflect.ValueOf(metrics).Elem().FieldByName("timestamp")
reflect.NewAt(rf.Type(), unsafe.Pointer(rf.UnsafeAddr())).Elem().Set(reflect.ValueOf(int64(0)))
```

to manually set the timestamp to `0`.

**Solution**

The cleanest solution would be to do the following:
1. Bump the MV to 2
2. Update `New` to use optional [functional options](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis) to allow users to customize the output writer and timestamp (and others in the future).
3. Remove `NewFor` as it is no longer needed.

A less clean but not requiring a MV bump option would be to add a `SetTimestamp` method on the `*Logger` that sets the timestamp.

Thoughts?

**Comment by prozz** [comment]
Glad you like the lib!

Functional options sound like a great idea! Happy to accept the PR :)

**Comment by harrisonhjones** [comment]
I'll work on it tomorrow then!

**Comment by prozz** [comment]
Thanks for your work on that. I really appreciate the effort!
