### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by kaihendry** [prozz/aws-embedded-metrics-golang#5]
I don't understand why you use MetricAs instead of .Metric

Be good to have some inline example in api doc.

For example with https://pkg.go.dev/github.com/prozz/aws-embedded-metrics-golang/emf#Logger.DimensionSet I was really confused that I needed emf.NewDimension.

**Comment by kaihendry** [comment]
Additionally it would be good to spot potentially incorrect usage of the API could be caught:

```
                // export some AWS metrics
-               emf.New().Namespace("loglint").Dimension("group", *logGroupName).
-                       Dimension("account", accountNumber).
+               emf.New().Namespace("loglint").DimensionSet(
+                       emf.NewDimension("group", *logGroupName),
+                       emf.NewDimension("account", accountNumber)).
                        Metric("someJSONStructure", gotStructure).Log()
```

Catch .Dimension chaining, when what you **really want is DimensionSet**!

**Comment by prozz** [comment]
> I don't understand why you use MetricAs instead of .Metric

`Metric*As` funcs take `MetricUnit` as an argument, those without `As` do not.

> Additionally it would be good to spot potentially incorrect usage of the API could be caught

I'm happy to accept PR that covers that issue :)

Overall this lib mimics EMF format, so having some knowledge of its structure makes it easier to understand what is going on.
